spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: 'true'
  jackson:
    serialization:
      fail-on-empty-beans: 'false'

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
  file:
    path: ${LOGGING_FILE_PATH}